[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.42.0",
    "nltk>=3.9.1",
    "pypdf2>=3.0.1",
    "reportlab>=4.2.5",
]
